// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ4ejPWREZzB4aEecswWXZfjYZnW-iwgs',
    appId: '1:556426016827:web:5096bc3c4954b01b8cc41e',
    messagingSenderId: '556426016827',
    projectId: 'traffix-flutter',
    authDomain: 'traffix-flutter.firebaseapp.com',
    storageBucket: 'traffix-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vh1Xt3jRKPdMvcoH-GBqNgs9zPYHUvA',
    appId: '1:556426016827:android:c35e7559976cd5e88cc41e',
    messagingSenderId: '556426016827',
    projectId: 'traffix-flutter',
    storageBucket: 'traffix-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNpUXQJAzhXe73gC6wqV8JKAykw3Hjab8',
    appId: '1:556426016827:ios:e0962a261386854f8cc41e',
    messagingSenderId: '556426016827',
    projectId: 'traffix-flutter',
    storageBucket: 'traffix-flutter.firebasestorage.app',
    iosBundleId: 'com.example.traffix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNpUXQJAzhXe73gC6wqV8JKAykw3Hjab8',
    appId: '1:556426016827:ios:e0962a261386854f8cc41e',
    messagingSenderId: '556426016827',
    projectId: 'traffix-flutter',
    storageBucket: 'traffix-flutter.firebasestorage.app',
    iosBundleId: 'com.example.traffix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ4ejPWREZzB4aEecswWXZfjYZnW-iwgs',
    appId: '1:556426016827:web:8f75dcc3a62c6e498cc41e',
    messagingSenderId: '556426016827',
    projectId: 'traffix-flutter',
    authDomain: 'traffix-flutter.firebaseapp.com',
    storageBucket: 'traffix-flutter.firebasestorage.app',
  );
}
